import { Course } from "./types";

type Lang = "no" | "en";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const LABELS = {
  no: {
    locale: "nb-NO",
    headerLine: (date: string, mastered: number, total: number) =>
      `Generert av Lærbar · ${date} · ${mastered} av ${total} konsepter mestret`,
    progress: (mastered: number, total: number, pct: number) =>
      `${mastered} av ${total} konsepter mestret (${pct}%)`,
    nextReview: "Neste repetisjon",
    masteredBadge: "Mestret",
    sectionUnmastered: "Ikke mestret ennå",
    sectionMastered: "Mestret",
    flashcardLabel: "Flashcard — klikk for å snu",
    showHint: "💡 Vis hint",
    hideHint: "▲ Skjul hint",
    tapForAnswer: "Trykk for svar →",
    titleSuffix: "Lærbar",
  },
  en: {
    locale: "en-US",
    headerLine: (date: string, mastered: number, total: number) =>
      `Generated by Lærbar · ${date} · ${mastered} of ${total} concepts mastered`,
    progress: (mastered: number, total: number, pct: number) =>
      `${mastered} of ${total} concepts mastered (${pct}%)`,
    nextReview: "Next review",
    masteredBadge: "Mastered",
    sectionUnmastered: "Not yet mastered",
    sectionMastered: "Mastered",
    flashcardLabel: "Flashcard — click to flip",
    showHint: "💡 Show hint",
    hideHint: "▲ Hide hint",
    tapForAnswer: "Tap for answer →",
    titleSuffix: "Lærbar",
  },
} as const;

export function generateHtml(course: Course, lang: Lang = "no"): string {
  const L = LABELS[lang];
  const mastered = course.concepts.filter((c) => c.mastered).length;
  const total = course.concepts.length;
  const pct = total > 0 ? Math.round((mastered / total) * 100) : 0;
  const date = new Date(course.created_at).toLocaleDateString(L.locale);

  function conceptHtml(c: Course["concepts"][number], i: number) {
    const srsLabel = c.mastered && c.srs
      ? `<span class="srs-date">${L.nextReview}: ${esc(new Date(c.srs.next_review).toLocaleDateString(L.locale))}</span>`
      : "";

    const hintHtml = c.hint
      ? `<span class="hint-toggle">${L.showHint}</span>
         <div class="hint-text">${esc(c.hint)}</div>`
      : "";

    return `
    <div class="concept-card ${c.mastered ? "mastered" : ""}">
      <div class="concept-header">
        <span class="concept-num">${c.mastered ? "✓" : i + 1}</span>
        <strong>${esc(c.title)}</strong>
        ${c.mastered ? `<span class="badge">${L.masteredBadge}</span>` : ""}
        ${srsLabel}
      </div>
      <div class="qa">
        <div class="question">❓ ${esc(c.question)}</div>
        <div class="answer">${esc(c.answer)}</div>
        ${hintHtml}
      </div>
      <div class="fc-section">
        <div class="fc-label">${L.flashcardLabel}</div>
        <div class="flashcard">
          <div class="fc-face fc-front">
            <span>${esc(c.flashcard_front)}</span>
            <span class="fc-tap-hint">${L.tapForAnswer}</span>
          </div>
          <div class="fc-face fc-back">
            <span>${esc(c.flashcard_back)}</span>
          </div>
        </div>
      </div>
    </div>`;
  }

  const masteredConcepts = course.concepts.filter((c) => c.mastered);
  const unmasteredConcepts = course.concepts.filter((c) => !c.mastered);

  const unmasteredHtml = unmasteredConcepts.length > 0
    ? `<div class="section-label">${L.sectionUnmastered} (${unmasteredConcepts.length})</div>
       ${unmasteredConcepts.map((c) => conceptHtml(c, course.concepts.indexOf(c))).join("\n")}`
    : "";

  const masteredHtml = masteredConcepts.length > 0
    ? `<div class="section-label">${L.sectionMastered} (${masteredConcepts.length})</div>
       ${masteredConcepts.map((c) => conceptHtml(c, course.concepts.indexOf(c))).join("\n")}`
    : "";

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(course.title)} — ${L.titleSuffix}</title>
<style>
  :root { --cream:#f5f0e8; --dg:#1a2e20; --mg:#2d4a35; --gold:#c9a84c; --lg:#3d6b4a; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: var(--cream); font-family: system-ui, sans-serif; color: #1a1a1a; min-height: 100vh; }
  header { background: var(--dg); color: var(--cream); padding: 24px 32px; border-bottom: 3px solid var(--gold); }
  header h1 { font-size: 1.5rem; margin-bottom: 4px; }
  header p { font-size: .85rem; opacity: .75; }
  main { max-width: 720px; margin: 0 auto; padding: 32px 20px; }

  .progress-wrap { margin-bottom: 28px; }
  .progress-text { font-size: .88rem; color: #555; margin-bottom: 6px; }
  .progress-bar { width: 100%; background: rgba(0,0,0,.08); border-radius: 999px; height: 6px; }
  .progress-fill { height: 6px; border-radius: 999px; background: var(--lg); }

  .section-label { font-size: .72rem; font-weight: 600; text-transform: uppercase; letter-spacing: .08em; color: var(--mg); margin: 28px 0 10px; }

  .concept-card { background: white; border-radius: 6px; border: 1px solid rgba(0,0,0,.08); padding: 20px; margin-bottom: 12px; }
  .concept-card.mastered { border-color: rgba(61,107,74,.3); background: #f0faf3; }
  .concept-header { display: flex; align-items: center; gap: 10px; margin-bottom: 14px; flex-wrap: wrap; }
  .concept-num { width: 24px; height: 24px; border-radius: 50%; background: rgba(0,0,0,.08); display: flex; align-items: center; justify-content: center; font-size: .75rem; font-weight: 600; flex-shrink: 0; }
  .mastered .concept-num { background: var(--lg); color: white; }
  .badge { font-size: .7rem; background: var(--lg); color: white; padding: 2px 8px; border-radius: 10px; }
  .srs-date { margin-left: auto; font-size: .75rem; color: #666; }

  .qa { margin-bottom: 14px; }
  .question { font-size: .88rem; font-weight: 500; color: var(--dg); margin-bottom: 8px; }
  .answer { font-size: .86rem; color: #333; line-height: 1.65; padding: 10px 14px; background: #fafaf8; border-radius: 4px; border-left: 3px solid var(--gold); }

  .hint-toggle { display: inline-block; margin-top: 10px; font-size: .8rem; color: var(--mg); cursor: pointer; border: 1px solid rgba(0,0,0,.12); padding: 3px 10px; border-radius: 20px; user-select: none; }
  .hint-toggle:hover { border-color: var(--gold); color: var(--dg); }
  .hint-text { display: none; margin-top: 8px; font-size: .84rem; color: #555; padding: 8px 12px; background: rgba(201,168,76,.08); border-radius: 4px; border-left: 2px solid var(--gold); font-style: italic; }

  .fc-section { margin-top: 14px; }
  .fc-label { font-size: .72rem; font-weight: 600; text-transform: uppercase; letter-spacing: .05em; color: var(--gold); margin-bottom: 8px; }
  .flashcard { cursor: pointer; border-radius: 6px; border: 1px solid rgba(201,168,76,.35); overflow: hidden; min-height: 64px; }
  .fc-face { display: none; padding: 14px 16px; font-size: .88rem; line-height: 1.55; }
  .fc-face.fc-front { display: flex; justify-content: space-between; align-items: center; background: rgba(201,168,76,.07); font-weight: 500; color: var(--dg); gap: 12px; }
  .fc-tap-hint { font-size: .75rem; color: #aaa; white-space: nowrap; flex-shrink: 0; }
  .flashcard.flipped .fc-front { display: none; }
  .flashcard.flipped .fc-back { display: block; background: var(--dg); color: var(--cream); }
</style>
</head>
<body>
<header>
  <h1>${esc(course.title)}</h1>
  <p>${L.headerLine(date, mastered, total)}</p>
</header>
<main>
  <div class="progress-wrap">
    <div class="progress-text">${L.progress(mastered, total, pct)}</div>
    <div class="progress-bar"><div class="progress-fill" style="width:${pct}%"></div></div>
  </div>
  ${unmasteredHtml}
  ${masteredHtml}
</main>
<script>
  (function() {
    var SHOW_HINT = ${JSON.stringify(L.showHint)};
    var HIDE_HINT = ${JSON.stringify(L.hideHint)};
    document.querySelectorAll('.hint-toggle').forEach(function(btn) {
      btn.addEventListener('click', function() {
        var hint = this.nextElementSibling;
        var visible = hint.style.display === 'block';
        hint.style.display = visible ? 'none' : 'block';
        this.textContent = visible ? SHOW_HINT : HIDE_HINT;
      });
    });
    document.querySelectorAll('.flashcard').forEach(function(card) {
      card.addEventListener('click', function() {
        this.classList.toggle('flipped');
      });
    });
  })();
</script>
</body>
</html>`;
}
